version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/azi-online.com/fullchain.pem:/etc/letsencrypt/live/azi-online.com/fullchain.pem
      - /etc/letsencrypt/live/azi-online.com/privkey.pem:/etc/letsencrypt/live/azi-online.com/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
